ALTER TABLE users ADD COLUMN email         VARCHAR(255) UNIQUE NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN updated_at    TIMESTAMP DEFAULT NOW();

-- Default empty string hatao ab
ALTER TABLE users ALTER COLUMN email DROP DEFAULT;
ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;